#!/bin/bash
# WSL shim for ntm --agy panes. Interop runs the Windows subscription binary
# as the Windows user. No CLIProxy. Model comes from ntm --agy=N:<id>.
exec /mnt/c/Users/{{WIN_USER}}/AppData/Local/agy/bin/agy.exe "$@"
